version: '3'
services:
    jupyter:
        image: jupyter/scipy-notebook
        ports:
            - 8000:8888
        volumes:
            - .:/home/jovyan
    postgres:
        build: docker/postgres 
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:
